### ISSUE TITLE
Not Able to Add Logo in the Slider 

### ISSUE THREAD

**Issue by arivu95** [timobaehr/auto_scaffold#1]
I am trying the possible ways to add the logo in our slider but not able to insert it due to restrictions. so please check and fix this bug.

**Comment by timobaehr** [comment]
You can add a logo to the slider. Can be any widget or even nothing:
```dart
AutoScaffold(
  ...,
  drawerLeading: Icon(Icons.favorite, color: Colors.red),
)
```

Or do I missunderstand your question?
